- CallsheetLocalizations/uk.xcloc/Localized Contents/uk.xliff
https://github.com/cliss/callsheet-localizations/pull/3#discussion_r1598511577
> ukrainian: better "Credits" translation

- README.md
I thought this might be helpful, but feel free to merge and change anything you want.
> Describe pluralization a bit more

- README.md
I didn't know these were different, but TIL.
> Update README.md for the right kind of ordinal

- CallsheetLocalizations/de.xcloc/Localized Contents/de.xliff
Pull request for whatever will come next; also, three changes got lost somewhere, so I recommit them here.
> Changes to German localisation

- CallsheetLocalizations/de.xcloc/Localized Contents/de.xliff
> Tiny fix German

- CallsheetLocalizations/uk.xcloc/Localized Contents/uk.xliff
less translation, more localization
---
btw, the age string on Cast's Born section doesn't seem to follow plural rules in the latest TestFlight build (2024.12 (3))
> Ukrainian: some new strings; tweak wording

- CallsheetLocalizations/de.xcloc/Localized Contents/de.xliff
Needed to rewrite one sentence as it just didn't feel right/capture the right mood. Added a period.
> German: Style and period.

- CallsheetLocalizations/pl.xcloc/Localized Contents/pl.xliff
Im just getting started here, but I'd like to see how things work in the actual app. Do you release a test flight build once you sync the translations? If you do, please send me an invite so I can see once it gets in there, I'm https://mastodon.social/@spitfire on mastodon
> Initial pieces of translation

- CallsheetLocalizations/ru.xcloc/Localized Contents/ru.xliff
First pass for Russian translation. I'll probably check everything again later, but a test build would be amazing. If you do end up making one, I'm [@gkeep@mastodon.social](https://mastodon.social/@gkeep)
I'm also an ATP member 😉
> Russian translation

- AppStore/Spanish/Description.iOS.txt
- AppStore/Spanish/Description.visionOS.txt
- AppStore/Spanish/PromoText.txt
- CallsheetLocalizations/es.xcloc/Localized Contents/es.xliff
- README.md
Done by a human being, not a pesky translation service from a fruit company
> Spanish Localization finished

- CallsheetLocalizations/fr.xcloc/Localized Contents/fr.xliff
As the title says, keep up the good work here, on ATP and on other shows
> French translation for the content of Callsheet

- CallsheetLocalizations/de.xcloc/Localized Contents/de.xliff
> German too long

- AppStore/Spanish/Description.iOS.txt
- AppStore/Spanish/Description.visionOS.txt
- CallsheetLocalizations/es.xcloc/Localized Contents/es.xliff
Adapt the language on the App Store descriptions to be a more natural one.
> App store description upgraded, some minor strings replaced

- CallsheetLocalizations/nl.xcloc/Localized Contents/nl.xliff
Hopefully this puts Dutch at 100%
> Dutch last entry

- README.md
@cliss @DonSqueak I think this is the intended guideline, but feel free to merge and change. I've seen this one come up three times now.
> Add gender guidelines.

- README.md
The first sentence, which I wrote, is bad.
> Small wordsmithing.

- CallsheetLocalizations/it.xcloc/Localized Contents/it.xliff
Sorry, I haven't catch up in a few days...
> IT strings from the last week

- CallsheetLocalizations/es.xcloc/Localized Contents/es.xliff
Casey wouldn't let John do any homework, but he surely make me do it. 
I'm going to stop pointing unlocalized string. Every time I do it, there is more homework for me. 
🤣
(and now, more seriously, I think with this one I fixed all the errors that I spotted, but I need a new test flight build to check them alltogether and give a second pass)
> Where to watch substrings - Spanish

- CallsheetLocalizations/uk.xcloc/Localized Contents/uk.xliff
Settings screen for spoilers tells a story in this locale:
- Summary: "They are finally getting married"
- Character name: "Secret Agent"
- Episode name: "Tragic Wedding"
> Ukrainian: some more new strings

- CallsheetLocalizations/he.xcloc/Localized Contents/he.xliff
I translated all of the strings to Hebrew (100% coverage).
May need to adjust some strings once I see everything in context (in-app on a real device).
BTW I'm a **huge** fan of ATP and a proud member!
> Hebrew translation, first pass

- CallsheetLocalizations/da.xcloc/Localized Contents/da.xliff
@cliss Just wanted to confirm, there's no need to touch the entries here: https://github.com/cliss/callsheet-localizations/blob/main/CallsheetLocalizations/da.xcloc/Localized%20Contents/da.xliff#L35-L62 right?
> Adds first handful of Danish translations

- CallsheetLocalizations/pt-PT.xcloc/Localized Contents/pt-PT.xliff
- CallsheetLocalizations/pt-PT.xcloc/Source Contents/Localizable.xcstrings
Portuguese (Portugal) further updates
> Portuguese (Portugal) further updates

- CallsheetLocalizations/ja.xcloc/Localized Contents/ja.xliff
Edited one phrase (testing commit)
> JA - First commit

- AppStore/Swedish/Description.iOS.txt
- AppStore/Swedish/Description.visionOS.txt
- AppStore/Swedish/PromoText.txt
- CallsheetLocalizations/sv.xcloc/Localized Contents/sv.xliff
> Add translations for Swedish

- CallsheetLocalizations/uk.xcloc/Localized Contents/uk.xliff
> uk: shorter IAP descriptions

- CallsheetLocalizations/nb-NO.xcloc/Localized Contents/nb-NO.xliff
- Change a word
- Clean up sentence structure
> Minor update to Norwegian localization

- CallsheetLocalizations/uk.xcloc/Localized Contents/uk.xliff
> uk: app language

- CallsheetLocalizations/he.xcloc/Localized Contents/he.xliff
Some small tweaks to Hebrew after being able to see the live app in TestFlight.
Hebrew should be 100% translated now :)
> [Hebrew] Tweaks

- CallsheetLocalizations/sv.xcloc/Localized Contents/sv.xliff
Here are the missing translations from `8e9c3c4`👍 #69
PS: I sent you the details for TestFlight over at Mastodon😎
> Swedish: Add translations for 8e9c3c4

- CallsheetLocalizations/he.xcloc/Localized Contents/he.xliff
Translate new subscription related strings (issue #69).
Fixes 1 string with a missing space.
> [Hebrew] Translate new subscription related strings (issue #69)

- CallsheetLocalizations/nl.xcloc/Localized Contents/nl.xliff
> Updates to Dutch localization (includes #69)

- CallsheetLocalizations/nl.xcloc/Localized Contents/nl.xliff
Some more consistency and clarity.
> Updates to Dutch localization

- CallsheetLocalizations/ko.xcloc/ko.xcloc/Localized Contents/ko.xliff
- CallsheetLocalizations/ko.xcloc/ko.xcloc/Source Contents/Flookup/en.lproj/InfoPlist.strings
- CallsheetLocalizations/ko.xcloc/ko.xcloc/Source Contents/Localizable.xcstrings
- CallsheetLocalizations/ko.xcloc/ko.xcloc/contents.json
Added some Korean translations. Still WIP, and need to figure out some punctuation differences for some phrases.
> Korean translation ongoing.

- CallsheetLocalizations/he.xcloc/Localized Contents/he.xliff
- Translated the new Theme related strings.
- Tweaked some awkward translations.
- Fixed a typo.
> [HE] Theme related translations and tweaks

- CallsheetLocalizations/nb-NO.xcloc/Localized Contents/nb-NO.xliff
- README.md
- Add theming localization to Norwegian
- Get Norwegian back to 100% on the README.
> Add theming localization to Norwegian.

- CallsheetLocalizations/es-MX.xcloc/Localized Contents/es-MX.xliff
@ccavazos @unaiherran please check these, thanks
> ES updates

- CallsheetLocalizations/pt-PT.xcloc/Localized Contents/pt-PT.xliff
Hi
@apfernandes please check this one. I was checking my work and it kept saying "o Callsheet", like "the Callsheet", but it didn't sound right to me. So I left it out. But this is a common Portuguese/English problem. Not sure what sounds best.
> Add some PT translations.

- CallsheetLocalizations/pt-PT.xcloc/Localized Contents/pt-PT.xliff
These are what the iOS preferences say in pt-PT. cc: @apfernandes
> Improve pt-PT dark and light theme translations.

- CallsheetLocalizations/nb-NO.xcloc/Localized Contents/nb-NO.xliff
Added new localizations after the latest app updates. I would expect another PR or two once this makes it into the TestFlight after seeing it in context... :)
> Add new localizations for Norwegian

- CallsheetLocalizations/de.xcloc/Localized Contents/de.xliff
- added a few entries in the german localization
> updated german localizations

- CallsheetLocalizations/de.xcloc/Localized Contents/de.xliff
Hi Casey,
as discussed via email on April 23, here are some improvements for your German localization strings. I will comment each change to explain to you why I think the new version is better. Feel free to reject changes by leaving a comment as well, I will then revert.
✌️
> Improve German localizations
